### ISSUE TITLE
java.lang.NoClassDefFoundError: java/sql/Time during buildWidgetSet

### ISSUE THREAD

**Issue by glebshalyganov** [cuba-platform/cuba-gradle-plugin#156]
### Environment

- Platform version: 7.2
- OS: Windows
- Java 11

### Description of the bug or enhancement

Create project with Maps add-on and Charts add-on. Add web-toolkit module. Build project.

- Expected behavior
Build successful.
- Actual behavior
buildWidgetSet task fails with the error:
```java
   Invoking Linker Export CompilationResult symbol maps
      [ERROR] Failed to link
java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.Gson.<init>(Gson.java:265)
	at com.google.gson.Gson.<init>(Gson.java:186)
	at com.google.gwt.thirdparty.debugging.sourcemap.SourceMapConsumerV3.parse(SourceMapConsumerV3.java:87)
	at com.google.gwt.thirdparty.debugging.sourcemap.SourceMapConsumerV3.parse(SourceMapConsumerV3.java:78)
	at com.google.gwt.thirdparty.debugging.sourcemap.SourceMapGeneratorV3.mergeMapSection(SourceMapGeneratorV3.java:311)
	at com.google.gwt.core.linker.SymbolMapsLinker.link(SymbolMapsLinker.java:316)
	at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.invokeLinkForOnePermutation(StandardLinkerContext.java:384)
	at com.google.gwt.dev.Link.finishPermutation(Link.java:483)
	at com.google.gwt.dev.Link.doSimulatedShardingLink(Link.java:445)
	at com.google.gwt.dev.Link.link(Link.java:178)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:244)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.haulmont.gradle.classpath.ClassPathCommandLine.invokeOriginalMainClass(ClassPathCommandLine.java:54)
	at com.haulmont.gradle.classpath.ClassPathCommandLine.main(ClassPathCommandLine.java:47)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more

Task :smarts-web-toolkit:buildWidgetSet FAILED
```

**Comment by reznikova21** [comment]
7.2-SNAPSHOT - verified
