### ISSUE TITLE
Support MySQL 8

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba-gradle-plugin#33]
### Environment

- Platform version: 6.8.7 
- Database: MySQL 

### Description of the bug or enhancement

- Minimal reproducible example

1) Download and install MySQL server
2) Download a new MySQL connector (mysql-connector-java-8.0.11 for instance)
3) Rename it and put to studio libs
4) take some project assemble and deploy it
5) Put the new connector to Tomcat libs
6) Adjust connection to MySQL DBMS
7) Create the database

- Expected behavior
The database would be created 

- Actual behavior
NPE in Gradle plugin 

```
Caused by: java.lang.NullPointerException
	at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:3005)
	at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1916)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1845)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1215)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
```

And the whole log: 
[graldeExc.txt](https://github.com/cuba-platform/cuba/files/1974383/graldeExc.txt)

**Comment by gorbunkov** [comment]
@IskandarovRost, does everything work with the connector 5.1?
