### ISSUE TITLE
Entity model isn't enhanced with enabled groovy support

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba-gradle-plugin#80]
### Environment

- Platform version: 7.0.BETA1

### Description of the bug or enhancement
- Minimal reproducible example
   - Create new project using CUBA STUDIO 
   - Extends User entity
   - Enable Groovy support for the project
   - Assemble and start project 
Test project: [sample70.zip](https://github.com/cuba-platform/cuba-gradle-plugin/files/2610676/sample70.zip)
- Expected behavior 
Entity User should be enhanced
- Actual behavior
User entity isn't enhanced. Exception in the log: 
```Caused by: org.eclipse.persistence.exceptions.ValidationException: 
Exception Description: The attribute [id] of class [com.company.sample70.entity.ExtUser] is mapped to a primary key column in the database. Updates are not allowed.
	at org.eclipse.persistence.exceptions.ValidationException.primaryKeyUpdateDisallowed(ValidationException.java:2551) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.writeFromObjectIntoRowWithChangeRecord(AbstractDirectMapping.java:1298) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildRowForUpdateWithChangeSet(ObjectBuilder.java:1776) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.updateObjectForWriteWithChangeSet(DatabaseQueryMechanism.java:1043) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
	at org.eclipse.persistence.queries.UpdateObjectQuery.executeCommitWithChangeSet(UpdateObjectQuery.java:84) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:314) ~[org.eclipse.persistence.core-2.7.2-2-cuba.jar:na]
```

**Comment by jreznot** [comment]
Please check 6.10 version too

**Comment by clumsym76** [comment]
This issue happens now with latest release 7.0.3

**Comment by dtsaryov** [comment]
@clumsym76 could you provide a sample to reproduce the problem?

**Comment by clumsym76** [comment]
Hello dear Cuba team, pls find the attached sample.

[sample.zip](https://github.com/cuba-platform/cuba-gradle-plugin/files/3028717/sample.zip)

**Comment by dtsaryov** [comment]
@clumsym76 it seems that your problem is not related to enhancing and groovy support, because groovy support is not enabled in the sample project.

I've extended the `User` entity and enabled Groovy support to check the case and everything is ok:

[groovy-support-test.zip](https://github.com/cuba-platform/cuba-gradle-plugin/files/3028927/groovy-support-test.zip)

Please create a topic on our support forum if the problem will not be solved: https://www.cuba-platform.com/discuss/

**Comment by clumsym76** [comment]
Thx, I see, I'll create a new topic then
