### ISSUE TITLE
Support uber jar building for app components that defines custom UI components

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba-gradle-plugin#97]
https://www.cuba-platform.com/discuss/t/pentaho-integration-bicomponent-not-working-on-uberjar-deployment-possible-bug/8205/4

### Environment

- Platform version: 6.10
### Description of the bug or enhancement

- Minimal reproducible example
  - Create app. Add admin tool addon (any other app component with custom UI component) and BI addon
  - Build uber jar and run
  - Try to open BI widget
- Actual behavior
```
Caused by: com.haulmont.cuba.gui.GuiDevelopmentException: Unknown component: biComponent
        at com.haulmont.cuba.gui.xml.layout.LayoutLoader.getLoader(LayoutLoader.java:57) ~[classes/:na]
        at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:92) ~[classes/:na]
        at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:69) ~[classes/:na]
        at com.haulmont.cuba.gui.xml.layout.loaders.VBoxLayoutLoader.createComponent(VBoxLayoutLoader.java:26) ~[classes/:na]
        at com.haulmont.cuba.gui.xml.layout.LayoutLoader.createComponent(LayoutLoader.java:94) ~[classes/:na]
        at com.haulmont.cuba.gui.xml.layout.loaders.ContainerLoader.createSubComponents(ContainerLoader.java:69) ~[classes/:na]
```

**Comment by kenince** [comment]
When is the 6.10.8 platform expected to be released?
